### ISSUE TITLE
Improper sniffing of architecture

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/environment-setup#8]
Correctly inferred I needed a .deb, but gave me amd64 to download instead of i386 or throwing an error.

**Comment by gj** [comment]
Hi @ArloJamesBarnes !

We don't provide a 32-bit version, but you're welcome to try installing a 32-bit version of Atom and [adding the appropriate packages](http://help.learn.co/the-learn-ide/the-basics-of-the-learn-ide/manually-install-the-learn-ide-from-atom). No guarantee about whether this will work, though. 😕

Sorry!
